add_newline = false
prompt_order = [
    "username",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "line_break",
    "jobs",
    "character",
]

[directory]
truncate_to_repo = false
truncation_length = 3
fish_style_pwd_dir_length = 1
style = "blue bold"

