# vim: ft=zsh
export MANPAGER='nvim +Man!'
export EDITOR=vim
export BROWSER=quteb

# path to my scripts
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# path to cargo(rust) local installed programs
export PATH="$HOME/.cargo/bin:$PATH"
# path to haskell toolchain
export PATH="$HOME/.ghcup/bin:$PATH"
# (not sure I need cabal path?)
export PATH="$HOME/.cabal/bin:$PATH"

# xdg specification
export XDG_CONFIG_HOME=~/.config
# make docker follow xdg
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
# make X11 follow xdg
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

# colorize broken (orphan) symlinks
export LS_COLORS='or=40;31;01'

# fzf settings
export FZF_DEFAULT_COMMAND='fd --type file --type symlink'
export FZF_DEFAULT_OPTS="--no-mouse --bind ctrl-s:toggle-sort \
                         --bind ctrl-t:track+clear-query"

# add ripgrep to 'progress' util
export PROGRESS_ARGS='-a rg'

# automatic startx on tty1
if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
      exec startx "$XDG_CONFIG_HOME/X11/xinitrc" -- -keeptty &> ~/.local/share/startx.log
fi
