# load plugins from antibody plugins manager
source ~/.local/share/zsh_plugins.sh
# Note: after changing plugins.txt you need to run:
# `antibody bundle < ~/.config/zsh/plugins.txt > ~/.local/share/zsh_plugins.sh`

source ~/.config/zsh/settings.zsh
source ~/.config/zsh/aliases/_main.zsh
source ~/.config/zsh/keys.zsh
# note: have to be always at the end
source ~/.config/zsh/prompt-highlight.zsh

precmd() {
    cur_fortune="$(fortune -s | tee -a /tmp/fortune-history)"
    ( (kitten icat --use-window-size 24,20,695,1135 /opt/terminal_image.png </dev/tty \
        && echo "$cur_fortune" && echo -n '% ') &)
    # ((kitten icat --place 24x20@0x0 /opt/terminal_image.png </dev/tty && tput cuf 2) &)
    # timg -I -gx20 -pk /opt/terminal_image.png
    # tput cup 20 0
    # fortune -s
    unfunction precmd
}
