# load plugins from antibody plugins manager
source ~/.local/share/zsh_plugins.sh
# Note: after changing plugins.txt you need to run:
# `antibody bundle < ~/.config/zsh/plugins.txt > ~/.local/share/zsh_plugins.sh`

source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/keys.zsh

# history settings
HISTFILE=~/.local/share/zsh_history
HISTSIZE=1000
SAVEHIST=100000
# append history entries immediately
# (also immediately import new commands from history file)
# setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
# ignore duplicates
setopt HIST_IGNORE_ALL_DUPS

# clear right-side prompt on pressing enter
setopt TRANSIENT_RPROMPT

fpath+=~/.zfunc
# The following lines were added by compinstall
zstyle :compinstall filename '~/.config/zsh/.zshrc'
autoload -Uz compinit
compinit -d ~/.cache/zcompdump
# End of lines added by compinstall

# rehash before each completion
zstyle ':completion:*' rehash true

# disable treating `!` character
# (so now can use '!' for excluding in globs)
unsetopt BANG_HIST

# prompt
PS1="%# "
RPS1="%(?..[%?%1v])"
