[theme]
name = "plain"
[theme.overrides]
separator = ""

[icons]
name = "awesome5"
[icons.overrides]
music = ""


[[block]]
block = "custom"
command = "tail -qn1 - ~/.goals"
interval = "once"

# [[block]]
# block = "net"
# device = "wlan0"
# interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}"
clickable = false
[[block]]
block = "memory"
display_type = "swap"
format_swap = "{swap_used;G}"
warning_swap = 1
critical_swap = 10
clickable = false

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"
[block.theme_overrides]
idle_fg = "#b58900"
warning_fg = "#93a1a1"

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{max} max"

[[block]]
block = "battery"
format = "{percentage}% {time}"
driver = "upower"
device = "DisplayDevice"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %l:%M"
