[theme]
theme = "plain"
[theme.overrides]
separator = ""

[icons]
icons = "awesome6"


[[block]]
block = "custom"
command = "rem | rg -qv 'No reminders\\.' && echo 'hvr'"
interval = 1800

[[block]]
block = "memory"
format = "$icon $mem_used.eng(hide_unit:true, width:3) "

[[block]]
block = "memory"
warning_swap = 1
critical_swap = 10
# TODO: want to hide swap on zero
format = "$icon_swap $swap_used.eng(hide_unit:true, width:1) "

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"
[block.theme_overrides]
# swap idle and warning to get warning when mic is *not* muted
idle_fg = { link = "warning_fg" }
idle_bg = { link = "warning_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }

[[block]]
block = "temperature"
interval = 5
format = " $icon $min, $max "

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
format = "$icon $percentage $time "
full_threshold = 100
full_format = "$icon  "
[block.theme_overrides]
idle_fg = { link = "good_fg" }

[[block]]
block = "time"
interval = 60
format = "$icon $timestamp.datetime(f:'%d/%m %a %-I:%M', l:ja_JP)"
