icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
separator = ""

[[block]]
block = "music"

[[block]]
block = "net"
device = "enp2s0"
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "time"
interval = 60
format = "%d.%m %a %H:%M"
#format = "%a %d/%m %R"

