icons = "awesome5"

[theme]
name = "plain"
[theme.overrides]
separator = ""


[[block]]
block = "custom_dbus"
name = "dstatus_text"

# [[block]]
# block = "music"
# max_width = 40
# dynamic_width = true

# [[block]]
# block = "net"
# device = "enp2s0"
# interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GiB"
format_swap = "{SUg}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "temperature"
collapsed = false
interval = 1

[[block]]
block = "battery"
format = "{percentage}% {time}"
driver = "upower"
device = "DisplayDevice"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
